version: 2

workflows:
  version: 2
  default:
    jobs:
      - "build-pbs"
      - "build-slurm"

jobs:
  "build-pbs":
    docker:
      - image: continuumio/miniconda:latest
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true 

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.1"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: 
          name: Install Docker Compose
          command: |
            set -x 
            VER="1.23.2"
            curl -L https://github.com/docker/compose/releases/download/$VER/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose



      - run:
          name: Check docker installation
          command: |
            docker version
            docker-compose version
      
      - run:
          name: Build PBS docker image 
          command: |
            cd ./pbs
            ./start-pbs.sh
            cd - 
            docker exec -it -u pbsuser pbs_master pbsnodes -a
            docker ps -a
            docker images

  "build-slurm":
    docker:
      - image: continuumio/miniconda:latest
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true 

      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.1"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      - run: 
          name: Install Docker Compose
          command: |
            set -x 
            VER="1.23.2"
            curl -L https://github.com/docker/compose/releases/download/$VER/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose



      - run:
          name: Check docker installation
          command: |
            docker version
            docker-compose version
      
      - run:
          name: Build Slurm docker image 
          command: |
            cd ./slurm
            ./start-pbs.sh
            cd - 
            docker exec -it -u pbsuser pbs_master pbsnodes -a
            docker ps -a
            docker images

     